# Form implementation generated from reading ui file 'blueberry2.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Blueberry(object):
    def setupUi(self, Blueberry):
        Blueberry.setObjectName("Blueberry")
        Blueberry.resize(764, 336)
        Blueberry.setMinimumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        Blueberry.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/blueberryImageCropped.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Blueberry.setWindowIcon(icon)
        Blueberry.setStyleSheet("background-color: #000000;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #0000FF;")
        self.centralwidget = QtWidgets.QWidget(parent=Blueberry)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.files = QtWidgets.QToolButton(parent=self.centralwidget)
        self.files.setMinimumSize(QtCore.QSize(30, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setItalic(False)
        self.files.setFont(font)
        self.files.setAutoFillBackground(False)
        self.files.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        self.files.setObjectName("files")
        self.horizontalLayout.addWidget(self.files)
        self.playlists = QtWidgets.QToolButton(parent=self.centralwidget)
        self.playlists.setMinimumSize(QtCore.QSize(40, 40))
        self.playlists.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        self.playlists.setObjectName("playlists")
        self.horizontalLayout.addWidget(self.playlists)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.arrow_left = QtWidgets.QPushButton(parent=self.centralwidget)
        self.arrow_left.setMinimumSize(QtCore.QSize(30, 30))
        self.arrow_left.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        self.arrow_left.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrow_left2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.arrow_left.setIcon(icon1)
        self.arrow_left.setObjectName("arrow_left")
        self.horizontalLayout.addWidget(self.arrow_left)
        self.play = QtWidgets.QPushButton(parent=self.centralwidget)
        self.play.setMinimumSize(QtCore.QSize(30, 30))
        self.play.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        self.play.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.play.setIcon(icon2)
        self.play.setObjectName("play")
        self.horizontalLayout.addWidget(self.play)
        self.arrow_right = QtWidgets.QPushButton(parent=self.centralwidget)
        self.arrow_right.setMinimumSize(QtCore.QSize(30, 30))
        self.arrow_right.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        self.arrow_right.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("arrow_right2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.arrow_right.setIcon(icon3)
        self.arrow_right.setObjectName("arrow_right")
        self.horizontalLayout.addWidget(self.arrow_right)
        self.stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stop.setMinimumSize(QtCore.QSize(30, 30))
        self.stop.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        self.stop.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("box2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stop.setIcon(icon4)
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.Slider = QtWidgets.QSlider(parent=self.centralwidget)
        self.Slider.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        self.Slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Slider.setObjectName("Slider")
        self.horizontalLayout.addWidget(self.Slider)
        self.label_0 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_0.setFont(font)
        self.label_0.setObjectName("label_0")
        self.horizontalLayout.addWidget(self.label_0)
        self.label_100 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.horizontalLayout.addWidget(self.label_100)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.repeat = QtWidgets.QPushButton(parent=self.widget)
        self.repeat.setMaximumSize(QtCore.QSize(100, 16777215))
        self.repeat.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("repeat.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.repeat.setIcon(icon5)
        self.repeat.setObjectName("repeat")
        self.horizontalLayout_2.addWidget(self.repeat)
        self.progressBar = QtWidgets.QProgressBar(parent=self.widget)
        self.progressBar.setMinimumSize(QtCore.QSize(100, 50))
        self.progressBar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.progressBar.setStyleSheet("background-color: #00008B;\n"
"border: 1px solid #000000;\n"
"border-radius: 4px;\n"
"color: #1E90FF;")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.widget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(30, 20))
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_2.addWidget(self.lcdNumber)
        self.verticalLayout.addWidget(self.widget)
        Blueberry.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Blueberry)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 22))
        self.menubar.setObjectName("menubar")
        Blueberry.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Blueberry)
        self.statusbar.setObjectName("statusbar")
        Blueberry.setStatusBar(self.statusbar)

        self.retranslateUi(Blueberry)
        QtCore.QMetaObject.connectSlotsByName(Blueberry)

    def retranslateUi(self, Blueberry):
        _translate = QtCore.QCoreApplication.translate
        Blueberry.setWindowTitle(_translate("Blueberry", "Blueberry"))
        self.files.setText(_translate("Blueberry", "Files"))
        self.playlists.setText(_translate("Blueberry", "Playlists"))
        self.label_0.setText(_translate("Blueberry", "0"))
        self.label_100.setText(_translate("Blueberry", "100"))
        self.repeat.setText(_translate("Blueberry", "Repeat"))
        self.arrow_left.setText(_translate("Blueberry", ""))
        self.arrow_right.setText(_translate("Blueberry", ""))
        self.play.setText(_translate("Blueberry", ""))
        self.stop.setText(_translate("Blueberry", ""))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Blueberry = QtWidgets.QMainWindow()
    ui = Ui_Blueberry()
    ui.setupUi(Blueberry)
    Blueberry.show()
    sys.exit(app.exec())
